export const AllCars = [
  {
    id: 1,
    title: "Koenigsegg",
    type: "Sport",
    gas: "90L",
    gear: "Manual",
    people: "2 People",
    price: "$99.00",
    image: "https://morent.ir/assets/cars/cr1.png",
  },
  {
    id: 2,
    title: "Nissan GT - R",
    type: "Sport",
    gas: "80L",
    gear: "Manual",
    people: "2 People",
    price: "$80.00",
    image: "https://morent.ir/assets/cars/cr2.png",
  },
  {
    id: 3,
    title: "Rolls - Royce",
    type: "Sedan",
    gas: "70L",
    gear: "Automatic",
    people: "4 People",
    price: "$96.00",
    image: "https://morent.ir/assets/cars/cr6.png",
  },
  {
    id: 4,
    title: "All New Rush",
    type: "SUV",
    gas: "60L",
    gear: "Automatic",
    people: "5 People",
    price: "$72.00",
    image: "https://morent.ir/assets/cars/cr5.png",
  },
  {
    id: 5,
    title: "CR-V",
    type: "SUV",
    gas: "80L",
    gear: "Manual",
    people: "6 People",
    price: "$72.00",
    image: "https://morent.ir/assets/cars/cr12.png",
  },
  {
    id: 6,
    title: "All New Terios",
    type: "SUV",
    gas: "80L",
    gear: "Manual",
    people: "6 People",
    price: "$82.00",
    image: "https://morent.ir/assets/cars/cr3.png",
  },
  {
    id: 7,
    title: "Ferrari 488 GTB",
    type: "Coupe",
    gas: "70L",
    gear: "Automatic",
    people: "2 People",
    price: "$99.00",
    image: "https://morent.ir/assets/cars/cr11.png",
  },
  {
    id: 8,
    title: "New MG ZS",
    type: "SUV",
    gas: "80L",
    gear: "Automatic",
    people: "6 People",
    price: "$80.00",
    image: "https://morent.ir/assets/cars/cr4.png",
  },
  {
    id: 9,
    title: "Mazda3",
    type: "Coupe",
    gas: "60L",
    gear: "Automatic",
    people: "4 People",
    price: "$75.00",
    image: "https://morent.ir/assets/cars/cr8.png",
  },
  {
    id: 10,
    title: "Mercedes-Benz EQS",
    type: "Sedan",
    gas: "EV",
    gear: "Automatic",
    people: "4 People",
    price: "$82.00",
    image: "https://morent.ir/assets/cars/cr9.png",
  },
  {
    id: 11,
    title: "Audi Q8",
    type: "Hatchback",
    gas: "70L",
    gear: "Manual",
    people: "4 People",
    price: "$90.00",
    image: "https://morent.ir/assets/cars/cr10.png",
  },
  {
    id: 12,
    title: " Bentley Continental GT",
    type: "Sedan",
    gas: "90L",
    gear: "Manual",
    people: "2 People",
    price: "$86.00",
    image: "https://morent.ir/assets/cars/cr7.png",
  },
];

export const PopularCars = [
  {
    id: 2,
    title: "Nissan GT - R",
    type: "Sport",
    gas: "80L",
    gear: "Manual",
    people: "2 People",
    price: "$80.00",
    image: "https://morent.ir/assets/cars/cr2.png",
  },
  {
    id: 1,
    title: "Koenigsegg",
    type: "Sport",
    gas: "90L",
    gear: "Manual",
    people: "2 People",
    price: "$99.00",
    image: "https://morent.ir/assets/cars/cr1.png",
  },
  {
    id: 3,
    title: "Rolls - Royce",
    type: "Sedan",
    gas: "70L",
    gear: "Automatic",
    people: "4 People",
    price: "$96.00",
    image: "https://morent.ir/assets/cars/cr6.png",
  },
  {
    id: 4,
    title: "All New Rush",
    type: "SUV",
    gas: "60L",
    gear: "Automatic",
    people: "5 People",
    price: "$72.00",
    image: "https://morent.ir/assets/cars/cr5.png",
  },
];
